### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kirksgithub**
Updated example docs with the latest wallet adapter specs

### CODE REVIEW

**Comment by jpbogle** [comment]
Thanks @kirksgithub, one comment was instead of casting ‘as Wallet’ interface it’s probably more typesafe to convert the object like so.

It’s weird the old versions had different concrete implementations of Wallet so we chose to make it take the interface. Maybe this new adapter has a similar interface we can ultimately switch to

‘’’ts
wallet={{
   signAllTransactions: async (txs: Transaction[]) => wallet.adapter.signAllTransactions(txs),
   signTransaction: async (tx: Transaction) => tx,
   publicKey: () => wallet.publicKey,
}}
‘’’

**Comment by kirksgithub** [comment]
I can confirm that this does not work tested both with same results (AccountConnect works **wallet={wallet.adapter as Wallet}** nevertheless ConnectTwitterButton with type safe is bringing a blank page on click)
`<div>
                {/* Account linking and wallet connector */}
                {
                <AccountConnect
                  connection={connection}
                  environment={'mainnet-beta'}
                  dark={true}
                  handleDisconnect={() => wallet.adapter.disconnect()}
                  wallet={wallet.adapter as Wallet}
                />
                }
                {/* Replace address with image */}
                <AddressImage address={publicKey} connection={connection} />
                {/* Replace address with name */}
                <DisplayAddress address={publicKey} connection={connection} />
                {/* Profile from address */}
                <ProfileSmall address={publicKey} connection={connection} />
                {/* Button to connect twitter profile */}
                
                <ConnectTwitterButton 
                  connection={connection} 
                  cluster={'mainnet-beta'}
                  wallet={wallet.adapter as Wallet} />
              </div>

                Using Typesafe WA
              <>
                {
                  <AccountConnect
                    connection={connection}
                    environment={'mainnet-beta'}
                    dark={true}
                    handleDisconnect={() => wallet.adapter.disconnect()}
                    wallet={{
                      signAllTransactions: async (txs: Transaction[]) => signAllTransactions(txs),
                      signTransaction: async (tx: Transaction) => tx,
                      publicKey: publicKey
                    }}
                  />
                  }
                  {/* Replace address with image */}
                  <AddressImage address={publicKey} connection={connection} />
                  {/* Replace address with name */}
                  <DisplayAddress address={publicKey} connection={connection} />
                  {/* Profile from address */}
                  <ProfileSmall address={publicKey} connection={connection} />
                  {/* Button to connect twitter profile */}
                  
                  <ConnectTwitterButton 
                    connection={connection} 
                    cluster={'mainnet-beta'}
                    wallet={{
                      signAllTransactions: async (txs: Transaction[]) => signAllTransactions(txs),
                      signTransaction: async (tx: Transaction) => tx,
                      publicKey: publicKey
                    }} />
              </>`

**Comment by kirksgithub** [comment]
Also tested with solanaProvider too (same exact result)
const solanaProvider = useWallet();


```
<>
                {/* Account linking and wallet connector */}
                {
                <AccountConnect
                  connection={connection}
                  environment={'mainnet-beta'}
                  dark={true}
                  handleDisconnect={() => wallet.adapter.disconnect()}
                  wallet={solanaProvider as Wallet
                  }
                />
                }
                {/* Replace address with image */}
                <AddressImage address={publicKey} connection={connection} />
                {/* Replace address with name */}
                <DisplayAddress address={publicKey} connection={connection} />
                {/* Profile from address */}
                <ProfileSmall address={publicKey} connection={connection} />
                {/* Button to connect twitter profile */}
                
                <ConnectTwitterButton 
                  connection={connection} 
                  cluster={'mainnet-beta'}
                  wallet={solanaProvider as Wallet} />
              </>

              <>
                {/* Account linking and wallet connector */}
                {
                <AccountConnect
                  connection={connection}
                  environment={'mainnet-beta'}
                  dark={true}
                  handleDisconnect={() => wallet.adapter.disconnect()}
                  wallet={wallet.adapter as Wallet
                  }
                />
                }
                {/* Replace address with image */}
                <AddressImage address={publicKey} connection={connection} />
                {/* Replace address with name */}
                <DisplayAddress address={publicKey} connection={connection} />
                {/* Profile from address */}
                <ProfileSmall address={publicKey} connection={connection} />
                {/* Button to connect twitter profile */}
                
                <ConnectTwitterButton 
                  connection={connection} 
                  cluster={'mainnet-beta'}
                  wallet={wallet.adapter as Wallet} />
              </>

                Using Typesafe WA
              <>
                {
                  <AccountConnect
                    connection={connection}
                    environment={'mainnet-beta'}
                    dark={true}
                    handleDisconnect={() => wallet.adapter.disconnect()}
                    wallet={solanaProvider as Wallet
                    }
                  />
                  }
                  {/* Replace address with image */}
                  <AddressImage address={publicKey} connection={connection} />
                  {/* Replace address with name */}
                  <DisplayAddress address={publicKey} connection={connection} />
                  {/* Profile from address */}
                  <ProfileSmall address={publicKey} connection={connection} />
                  {/* Button to connect twitter profile */}
                  
                  <ConnectTwitterButton 
                    connection={connection} 
                    cluster={'mainnet-beta'}
                    wallet={{
                      signAllTransactions: async (txs: Transaction[]) => signAllTransactions(txs),
                      signTransaction: async (tx: Transaction) => tx,
                      publicKey: publicKey
                    }} />
              </>
```

**Comment by jpbogle** [comment]
@kirksgithub Not sure what you mean exactly by blank page in this one

>I can confirm that this does not work tested both with same results (AccountConnect works wallet={wallet.adapter as Wallet} nevertheless ConnectTwitterButton with type safe is bringing a blank page on click)

Are you saying it when casting `as Wallet` but not when using a typed object?

Also fwiw I did type out the `signAllTransactions` but that should also be included in the wallet interface. Its basically just passing through those methods into a new object

**Comment by gchatz22** [comment]
Closing due to inactivity

**Pull request closed without merging**
